### ISSUE TITLE
Android Improvements

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#1599]
There are a couple of things to improve
- [x] Improve handling of gradle files/custom gradle templates: https://github.com/getsentry/sentry-unity/issues/1477
- [x] Fixing proguard upload: https://github.com/getsentry/sentry-unity/issues/1439
- [x] Failures when running Sentry CLI should get treated as warnings and cli logs should get written back in the editor console:  https://github.com/getsentry/sentry-unity/issues/1339
- [x] A way to set the order of build https://github.com/getsentry/sentry-unity/issues/1411
