### ISSUE TITLE
Avoid DLL conflict with other Unity packages

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#300]
To avoid the _Multiple precompiled assemblies with the same name_ issue [we document a work around on the docs](https://docs.sentry.io/platforms/unity/troubleshooting/#precompiledassemblyexception-multiple-precompiled-assemblies-with-the-same-name)

## Discarded

 * ILMerge is archived. eg [doesn't support portable PDBs](https://github.com/dotnet/ILMerge/issues/11) and hasissues running on non windows.
 * [ILRepack](https://github.com/gluck/il-repack) is no longer being actively maintained. eg [has issues with netstandard on mac](https://github.com/gluck/il-repack/issues/243)
 * [Linker](https://github.com/dotnet/linker) is not designed to mitigate assembly loading conflicts

## Current approach

A new project that performs "assembly aliasing": https://github.com/getsentry/dotnet-assembly-alias

## TODO

 * [x] close the [current PR](https://github.com/getsentry/sentry-unity/pull/397) has to much noise in changes and commits.
 * [x] do a new PR with only required changes. also include a build step in GH actions to perform the aliasing as part of a build step
 * [ ] Do a release of Sentry.Unity
 * [ ] Request for some customers to smoke test

This issue is an alternative to #279

**Comment by SimonCropp** [comment]
@bruno-garcia what assembles are the ones that most commonly cause conflicts?

**Comment by bitsandfoxes** [comment]
We don't really have enough data to have common culprits. There were a few issues where `System.Buffers.dll` and `System.Threading.Task.Extension.dll` got named.

**Comment by SimonCropp** [comment]
yeah. i did some more research and noticed those. i will have a go at merging them tomorrow

**Comment by bruno-garcia** [comment]
@bitsandfoxes Unity devs use .NET logging libraries? I assumed it didn't so far and never thought about `SentryUnity` ever getting used in combination with anything from the `Sentry for .NET SDK` side of things.

> The reason i ask is that any merging changes in unity will result in either a different Sentry.dll (refs merged), or no Sentry.dll (merge it and other refs into the top level Sentry.Unity.* package)

Given the problem this solves is huge for Unity consumers, it sounds like an good trade off.

**Comment by SimonCropp** [comment]
@bruno-garcia i updated the description based on our conversation. can u take a look and edit/add anything i missed

**Comment by bruno-garcia** [comment]
Resolved on release 0.7.0

**Comment by bruno-garcia** [comment]
We wrote a blog post about how we solved this problem: https://blog.sentry.io/2022/02/24/alias-an-approach-to-net-assembly-conflict-resolution
