### ISSUE TITLE
Improve Android native support

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#320]
#307 added initial support

Follow up items

- [x] Upload SDK symbols with Craft on each release (PR: https://github.com/getsentry/sentry-unity/pull/324)
- [ ] Add missing options to the Android SDK #621
- [ ] Expose a way to add BeforeSend via Java/Kotlin (same for C#) #620
  * The goal is to avoid users from taking the "Manual Init" approach so we can rely on the options at build time
- [x] Hook into `crashedLastRun` to mark sessions as crashed
   * When adding the bridge to the options, set this property (https://github.com/getsentry/sentry-dotnet/blob/a79d46e62525cecaf7c7752f122268245f832b59/src/Sentry/SentryOptions.cs#L567) to a method that calls through the native bridge to the native equivalent
- [x] Add Gradle plugin to upload symbols of final game (or use MSBuild wrapping sentry-cli, part of this PR)
  * Example modifying `gradle.build` [here](https://github.com/getsentry/sentry-unity/blob/fd4a26e239d18865f1c947e3551178a1cde00120/src/Sentry.Unity.Editor/AndroidManifestConfiguration.cs#L29-L45)
- [x] Add scope sync (PR https://github.com/getsentry/sentry-unity/pull/308/ ) 
- [x] Remove `-SNAPSHOT` from the Android SDK name before building (will not have when using a tag)
- [x] Update commit sha to latest android release
- [x] Close this issue if not running into the same problem -> https://github.com/getsentry/sentry-java/pull/1594
- [x] Set breadcrumb level
- [ ] Default UserId in events from C# and Android don't match (installation_id) #606

**Comment by bitsandfoxes** [comment]
Superseded by individual issues.
