### ISSUE TITLE
Windows native support

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#527]
## Requirements: 

- Capturing native errors
- Capturing minidumps: https://github.com/getsentry/sentry-unity/issues/94
- Sync scope from Unity SDK to native SDK
- `crashed last run` functionality to track healthy sessions
Currently not supported by the native SDK 

## Things to consider:

- Breakpad
  - Less robust than Crashpad but does not require additional executable shipped with the build output
- Crashpad
  - Requires shipping with a `crashpad_handler.exe` with the build output
  - Users might not want to do that 
- We could offer a toggle between those two in addition to `Enable Window Native Support`? 

## TODOs and open questions:
* [x] Initial support for x86_64 IL2CPP + crasphad: #380
* [x] implement NativeScopeObserver (scope, breadcrumbs, extra, ...) - #546
* [x] do we want to support x86 & ARM64? -- wait for the real interest from the userbase
* [x] does it make sense to run with Mono scripting backend?
* [x] logging from native to the debug logger in the managed code? I don't think I've seen that in other integrations either... #577 
* [x] unit tests for the native crashes? #577 
* [x] upload symbols using CLI #607
* [ ] add call to `sentry_init` in the `main` function at compile time
* [x] `bool CrashedLastRun()` #615 
* [x] Packaging requires change in CI: We need artifacts from Mac and Windows so packaging requires a new job dependant on those - #547 
* [ ] Documentation

**Comment by bruno-garcia** [comment]
Regarding initializing the code in the Launcher instead of after the engine runs, we're investigating (#622) recompiling the playback engine (game executable). That's documented here: https://docs.unity.cn/Manual/WindowsStandaloneBinaries.html

**Comment by bruno-garcia** [comment]
Opened an issue to the follow up change
